from datetime import date, datetime
from decimal import Decimal

from django.urls import reverse
from rest_framework.test import APITestCase

from apps.ledger.models import (
    Contract,
    ContractStatus,
    Notification,
    Party,
    PartyType,
    PaymentChannel,
    Transaction,
    TransactionStatus,
    TransactionType,
)


class LedgerWorkflowApiTests(APITestCase):
    def setUp(self):
        self.landlord = Party.objects.create(
            name='Hari',
            username='hari_landlord',
            party_type=PartyType.LANDLORD,
        )
        self.client_party = Party.objects.create(
            name='Sita',
            username='sita_client',
            party_type=PartyType.CLIENT,
        )
        self.municipality = Party.objects.create(
            name='Kathmandu Ward 5',
            username='ward5_admin',
            party_type=PartyType.MUNICIPALITY,
        )
        self.contract = Contract.objects.create(
            landlord=self.landlord,
            client=self.client_party,
            municipality=self.municipality,
            start_date=date(2026, 1, 1),
            end_date=date(2028, 12, 31),
            base_rent=Decimal('25000.00'),
            annual_increment_percent=Decimal('5.00'),
            recurring_charges=[
                {
                    'label': 'Monthly Rent',
                    'amount': 25000,
                    'is_auto_increment': True,
                },
                {
                    'label': 'Electricity',
                    'amount': 2500,
                    'is_auto_increment': False,
                },
            ],
        )

    def _create_tx(self, tx_type: str, amount: str, occurred_at: datetime) -> Transaction:
        return Transaction.objects.create(
            contract=self.contract,
            transaction_type=tx_type,
            charge_label=tx_type.replace('_', ' ').title(),
            status=TransactionStatus.PENDING,
            amount=Decimal(amount),
            payer=self.client_party,
            payee=self.landlord,
            payment_channel=PaymentChannel.WALLET,
            payment_reference=f'REF-{tx_type}-{amount}',
            occurred_at=occurred_at,
        )

    def test_contract_code_is_autogenerated(self):
        self.assertTrue(self.contract.code.startswith('CTR-'))

    def test_returns_aggregated_summary_for_date_range(self):
        self._create_tx(TransactionType.RENT, '25000.00', datetime(2026, 4, 1, 8, 0))
        self._create_tx(TransactionType.ELECTRICITY, '2500.00', datetime(2026, 4, 2, 8, 0))
        self._create_tx(TransactionType.WATER, '500.00', datetime(2026, 3, 1, 8, 0))

        url = reverse('summary-list')
        response = self.client.get(
            url,
            {
                'username': self.landlord.username,
                'contract_id': self.contract.id,
                'start': '2026-04-01',
                'end': '2026-04-30',
            },
        )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data['count'], 2)
        self.assertEqual(Decimal(response.data['total']), Decimal('27500.00'))

    def test_client_can_claim_transaction(self):
        transaction = self._create_tx(
            TransactionType.RENT,
            '25000.00',
            datetime(2026, 4, 1, 8, 0),
        )

        url = reverse('transaction-claim', kwargs={'pk': transaction.pk})
        response = self.client.post(url, {'username': self.client_party.username}, format='json')

        transaction.refresh_from_db()
        self.assertEqual(response.status_code, 200)
        self.assertEqual(transaction.status, TransactionStatus.CLAIMED)
        self.assertEqual(transaction.claimed_by, self.client_party)
        self.assertTrue(
            Notification.objects.filter(
                recipient=self.landlord,
                transaction=transaction,
            ).exists()
        )

    def test_landlord_can_approve_claimed_transaction(self):
        transaction = self._create_tx(
            TransactionType.RENT,
            '25000.00',
            datetime(2026, 4, 1, 8, 0),
        )
        transaction.claim(self.client_party)

        url = reverse('transaction-approve', kwargs={'pk': transaction.pk})
        response = self.client.post(url, {'username': self.landlord.username}, format='json')

        transaction.refresh_from_db()
        self.assertEqual(response.status_code, 200)
        self.assertEqual(transaction.status, TransactionStatus.APPROVED)
        self.assertEqual(transaction.approved_by, self.landlord)
        self.assertTrue(
            Notification.objects.filter(
                recipient=self.municipality,
                transaction=transaction,
                title='Contract Ledger Updated',
            ).exists()
        )

    def test_municipality_cannot_approve_transaction(self):
        transaction = self._create_tx(
            TransactionType.RENT,
            '25000.00',
            datetime(2026, 4, 1, 8, 0),
        )
        transaction.claim(self.client_party)

        url = reverse('transaction-approve', kwargs={'pk': transaction.pk})
        response = self.client.post(url, {'username': self.municipality.username}, format='json')

        self.assertEqual(response.status_code, 403)

    def test_landlord_can_approve_contract(self):
        url = reverse('contract-approve', kwargs={'pk': self.contract.pk})
        response = self.client.post(url, {'username': self.landlord.username}, format='json')

        self.contract.refresh_from_db()
        self.assertEqual(response.status_code, 200)
        self.assertEqual(self.contract.status, ContractStatus.ACTIVE)

    def test_landlord_can_create_contract_with_dynamic_terms(self):
        url = reverse('contract-list')
        response = self.client.post(
            url,
            {
                'username': self.landlord.username,
                'client_id': self.client_party.id,
                'municipality_id': self.municipality.id,
                'start_date': '2026-05-01',
                'end_date': '2027-04-30',
                'base_rent': '30000.00',
                'annual_increment_percent': '7.50',
                'recurring_charges': [
                    {
                        'label': 'Monthly Rent',
                        'amount': 30000,
                        'is_auto_increment': True,
                    },
                    {
                        'label': 'Internet',
                        'amount': 1800,
                        'is_auto_increment': False,
                    },
                ],
                'optional_terms': ['Internet billed monthly to client'],
            },
            format='json',
        )

        self.assertEqual(response.status_code, 201)
        self.assertEqual(response.data['client']['id'], self.client_party.id)
        self.assertEqual(response.data['recurring_charges'][1]['label'], 'Internet')
        self.assertTrue(
            Notification.objects.filter(
                recipient=self.client_party,
                contract__code=response.data['code'],
                title='New Contract Shared',
            ).exists()
        )

    def test_client_can_submit_payment_for_due_item(self):
        url = reverse('contract-pay', kwargs={'pk': self.contract.pk})
        response = self.client.post(
            url,
            {
                'username': self.client_party.username,
                'contract_id': self.contract.id,
                'charge_label': 'Monthly Rent',
                'amount': '5000.00',
            },
            format='json',
        )

        self.assertEqual(response.status_code, 201)
        self.assertEqual(response.data['charge_label'], 'Monthly Rent')
        self.assertEqual(response.data['status'], TransactionStatus.CLAIMED)
        self.assertTrue(
            Notification.objects.filter(
                recipient=self.landlord,
                transaction__payment_reference=response.data['payment_reference'],
                title='Payment Waiting Approval',
            ).exists()
        )
