import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../../models/contract.dart';
import '../../routes/app_pages.dart';
import '../../controllers/overview_controller.dart';

class ContractsTab extends StatelessWidget {
  const ContractsTab({super.key});

  @override
  Widget build(BuildContext context) {
    final controller = Get.find<OverviewController>();

    return Obx(() {
      final user = controller.user;
      final contracts = controller.contracts;

      return ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  'Contracts',
                  style: Theme.of(context).textTheme.headlineSmall,
                ),
              ),
              if (user?.isLandlord == true)
                FilledButton.icon(
                  onPressed: () => Get.toNamed(AppPages.createContract),
                  icon: const Icon(Icons.add),
                  label: const Text('Add Contract'),
                ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            'Contract codes are autogenerated by the backend when a landlord creates a new property contract.',
            style: Theme.of(context).textTheme.bodyMedium,
          ),
          const SizedBox(height: 16),
          ...contracts.map(
            (contract) => Card(
              child: Padding(
                padding: const EdgeInsets.all(14),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      contract.code,
                      style: Theme.of(context).textTheme.titleLarge,
                    ),
                    const SizedBox(height: 6),
                    Text('Landlord: ${contract.landlord.name}'),
                    Text('Client: ${contract.client.name}'),
                    Text('Municipality: ${contract.municipality.name}'),
                    Text('Status: ${_statusLabel(contract.status)}'),
                    Text(
                      'Rent today: NPR ${contract.rentForDate(DateTime.now()).toStringAsFixed(0)}',
                    ),
                    if (contract.recurringCharges.isNotEmpty) ...[
                      const SizedBox(height: 8),
                      Text(
                        'Recurring charges',
                        style: Theme.of(context).textTheme.titleMedium,
                      ),
                      const SizedBox(height: 4),
                      ...contract.recurringCharges.map(
                        (charge) => Text(
                          '${charge.label}: NPR ${contract.chargeAmountForDate(charge, DateTime.now()).toStringAsFixed(0)}${charge.isAutoIncrement ? ' (auto increment)' : ''}',
                        ),
                      ),
                    ],
                    if (contract.optionalTerms.isNotEmpty) ...[
                      const SizedBox(height: 8),
                      Text(
                        'Optional terms',
                        style: Theme.of(context).textTheme.titleMedium,
                      ),
                      const SizedBox(height: 4),
                      ...contract.optionalTerms.map((term) => Text('- $term')),
                    ],
                    const SizedBox(height: 10),
                    if (user?.isLandlord == true && contract.isPendingApproval)
                      FilledButton(
                        onPressed: () => controller.approveContract(contract.backendId),
                        child: const Text('Approve Contract'),
                      ),
                    if (user?.isMunicipality == true)
                      const Chip(
                        label: Text('Municipality can review but not edit'),
                      ),
                  ],
                ),
              ),
            ),
          ),
          if (contracts.isEmpty)
            const Card(
              child: ListTile(
                title: Text('No contracts available for this user.'),
              ),
            ),
        ],
      );
    });
  }

  String _statusLabel(ContractStatus status) {
    switch (status) {
      case ContractStatus.pendingApproval:
        return 'Pending Approval';
      case ContractStatus.active:
        return 'Active';
      case ContractStatus.expired:
        return 'Expired';
    }
  }
}
