# Generated by Django 5.2.1 on 2026-04-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('landlord', 'Landlord'), ('client', 'Client'), ('municipality', 'Municipality')], max_length=32)),
                ('government_identifier', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_increment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_contracts', to='ledger.party')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_contracts', to='ledger.party')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipality_contracts', to='ledger.party')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('water', 'Water'), ('waste_management', 'Waste Management')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('disputed', 'Disputed')], default='pending', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_channel', models.CharField(choices=[('fonepay', 'Fonepay'), ('wallet', 'Wallet'), ('bank_transfer', 'Bank Transfer')], max_length=32)),
                ('payment_reference', models.CharField(max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.contract')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='ledger.party')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='ledger.party')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.party')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ledger.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
