# Generated by Django 5.2.1 on 2026-05-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_landlord_client_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ledger.party',),
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ledger.party',),
        ),
    ]
